### PR TITLE
Add types and ament_mypy to rpyutils.

### PR DESCRIPTION
**Pull request by InvincibleRMC**

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by fujitatomoya** [comment]
Pulls: ros2/rpyutils#12
Gist: https://gist.githubusercontent.com/fujitatomoya/cdd325d171bc435fbe53b305f1b61129/raw/32ffc632328a154422975d5de38f938b0aec542e/ros2.repos
BUILD args:  --packages-above-and-dependencies rpyutils
TEST args:  --packages-above rpyutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14481
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21752/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16026/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1256/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22454/)

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
@mergifyio update

**Comment by sloretz** [comment]
Pulls: https://github.com/ros2/rpyutils/pull/12
Gist: https://gist.githubusercontent.com/sloretz/50b73a68b805443735833030da7db60c/raw/32ffc632328a154422975d5de38f938b0aec542e/ros2.repos
BUILD args:  --packages-above-and-dependencies rpyutils
TEST args:  --packages-above rpyutils
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14524
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21800/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16071/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1303/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22501/)

**Pull request merged**
